apiVersion: apps/v1
kind: Deployment
metadata:
  name: seongjae-msa-product-depl
  namespace: seongjae-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seongjae-msa-product
  template:
    metadata:
      labels:
        app: seongjae-msa-product
    spec:
      containers:
      - name: seongjae-order-backend
        image: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com/seongjae-msa-product:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: seongjae-app-secrets
              key: DB_HOST
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: seongjae-app-secrets
              key: DB_PW
        - name: AWS_KEY
          valueFrom:
            secretKeyRef:
              name: seongjae-app-secrets
              key: AWS_KEY
        - name: AWS_SECRET
          valueFrom:
            secretKeyRef:
              name: seongjae-app-secrets
              key: AWS_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: seongjae-msa-product-service
  namespace: seongjae-ns
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: seongjae-msa-product